"""Pre-built encoding presets."""

ENCODING_PRESETS = {
    "quality": {
        "draft": {
            "description": "Quick preview, lowest quality",
            "video_codec": "libx264",
            "crf": 28,
            "preset": "ultrafast",
            "audio_codec": "aac",
            "audio_bitrate": "96k",
            "command_snippet": "-c:v libx264 -crf 28 -preset ultrafast -c:a aac -b:a 96k",
        },
        "standard": {
            "description": "Balanced quality and size",
            "video_codec": "libx264",
            "crf": 23,
            "preset": "medium",
            "audio_codec": "aac",
            "audio_bitrate": "128k",
            "command_snippet": "-c:v libx264 -crf 23 -preset medium -c:a aac -b:a 128k",
        },
        "high": {
            "description": "High quality output",
            "video_codec": "libx264",
            "crf": 18,
            "preset": "slow",
            "audio_codec": "aac",
            "audio_bitrate": "256k",
            "command_snippet": "-c:v libx264 -crf 18 -preset slow -c:a aac -b:a 256k",
        },
        "lossless": {
            "description": "Visually lossless",
            "video_codec": "libx264",
            "crf": 0,
            "preset": "veryslow",
            "audio_codec": "flac",
            "command_snippet": "-c:v libx264 -crf 0 -preset veryslow -c:a flac",
        },
    },
    "platform": {
        "youtube": {
            "description": "Optimized for YouTube",
            "video_codec": "libx264",
            "crf": 18,
            "preset": "slow",
            "profile": "high",
            "level": "4.2",
            "audio_codec": "aac",
            "audio_bitrate": "192k",
            "pixel_format": "yuv420p",
            "faststart": True,
            "command_snippet": "-c:v libx264 -crf 18 -preset slow -profile:v high -level:v 4.2 -pix_fmt yuv420p -c:a aac -b:a 192k -movflags +faststart",
        },
        "twitter": {
            "description": "Optimized for Twitter/X",
            "video_codec": "libx264",
            "crf": 23,
            "preset": "medium",
            "max_bitrate": "5M",
            "audio_codec": "aac",
            "audio_bitrate": "128k",
            "max_duration": 140,
            "command_snippet": "-c:v libx264 -crf 23 -preset medium -maxrate 5M -bufsize 10M -c:a aac -b:a 128k",
        },
        "instagram": {
            "description": "Optimized for Instagram",
            "video_codec": "libx264",
            "crf": 23,
            "preset": "medium",
            "audio_codec": "aac",
            "audio_bitrate": "128k",
            "pixel_format": "yuv420p",
            "command_snippet": "-c:v libx264 -crf 23 -preset medium -pix_fmt yuv420p -c:a aac -b:a 128k",
        },
        "tiktok": {
            "description": "Optimized for TikTok",
            "video_codec": "libx264",
            "crf": 23,
            "preset": "medium",
            "resolution": "1080x1920",
            "audio_codec": "aac",
            "audio_bitrate": "128k",
            "command_snippet": "-c:v libx264 -crf 23 -preset medium -vf scale=1080:1920 -c:a aac -b:a 128k",
        },
        "discord": {
            "description": "Optimized for Discord (8MB limit for free)",
            "video_codec": "libx264",
            "crf": 28,
            "preset": "medium",
            "audio_codec": "aac",
            "audio_bitrate": "96k",
            "note": "Adjust CRF based on duration to fit 8MB",
            "command_snippet": "-c:v libx264 -crf 28 -preset medium -c:a aac -b:a 96k",
        },
    },
    "codec": {
        "h264_compatible": {
            "description": "Maximum compatibility H.264",
            "video_codec": "libx264",
            "profile": "baseline",
            "level": "3.0",
            "pixel_format": "yuv420p",
            "command_snippet": "-c:v libx264 -profile:v baseline -level:v 3.0 -pix_fmt yuv420p",
        },
        "h265_efficient": {
            "description": "HEVC for smaller files",
            "video_codec": "libx265",
            "crf": 28,
            "preset": "medium",
            "command_snippet": "-c:v libx265 -crf 28 -preset medium",
        },
        "vp9_web": {
            "description": "VP9 for web (WebM)",
            "video_codec": "libvpx-vp9",
            "crf": 30,
            "audio_codec": "libopus",
            "command_snippet": "-c:v libvpx-vp9 -crf 30 -b:v 0 -c:a libopus",
        },
        "prores_editing": {
            "description": "ProRes for editing",
            "video_codec": "prores_ks",
            "profile": "3",  # ProRes 422 HQ
            "audio_codec": "pcm_s16le",
            "command_snippet": "-c:v prores_ks -profile:v 3 -c:a pcm_s16le",
        },
    },
    "resolution": {
        "4k": {
            "description": "4K UHD (3840x2160)",
            "width": 3840,
            "height": 2160,
            "filter": "scale=3840:2160:force_original_aspect_ratio=decrease,pad=3840:2160:(ow-iw)/2:(oh-ih)/2",
        },
        "1080p": {
            "description": "Full HD (1920x1080)",
            "width": 1920,
            "height": 1080,
            "filter": "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2",
        },
        "720p": {
            "description": "HD (1280x720)",
            "width": 1280,
            "height": 720,
            "filter": "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2",
        },
        "480p": {
            "description": "SD (854x480)",
            "width": 854,
            "height": 480,
            "filter": "scale=854:480:force_original_aspect_ratio=decrease,pad=854:480:(ow-iw)/2:(oh-ih)/2",
        },
        "vertical_1080": {
            "description": "Vertical 9:16 (1080x1920)",
            "width": 1080,
            "height": 1920,
            "filter": "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2",
        },
        "square_1080": {
            "description": "Square 1:1 (1080x1080)",
            "width": 1080,
            "height": 1080,
            "filter": "scale=1080:1080:force_original_aspect_ratio=decrease,pad=1080:1080:(ow-iw)/2:(oh-ih)/2",
        },
    },
    "special": {
        "gif": {
            "description": "Animated GIF",
            "format": "gif",
            "fps": 10,
            "width": 480,
            "filter": "fps=10,scale=480:-1:flags=lanczos",
            "note": "Use palette generation for best quality",
        },
        "thumbnail": {
            "description": "Video thumbnail extraction",
            "frames": 1,
            "format": "image2",
            "filter": "scale=1280:-1",
            "command_snippet": "-vframes 1",
        },
        "audio_only": {
            "description": "Extract audio as MP3",
            "audio_codec": "libmp3lame",
            "audio_bitrate": "192k",
            "command_snippet": "-vn -c:a libmp3lame -b:a 192k",
        },
    },
}
