"""Handler modules — re-exports all _f_* handlers for composer.py."""

from .audio import (  # noqa: F401
    _f_volume,
    _f_normalize,
    _f_fade_audio,
    _f_remove_audio,
    _f_extract_audio,
    _f_replace_audio,
    _f_audio_crossfade,
)

from .composite import (  # noqa: F401
    _f_add_text,
    _f_grid,
    _f_slideshow,
    _f_overlay_image,
    _f_watermark,
    _f_concat,
    _f_xfade,
    _f_split_screen,
    _f_animated_overlay,
    _f_text_overlay,
    _f_pip,
    _f_burn_subtitles,
    _f_countdown,
    _f_animated_text,
    _f_scrolling_text,
    _f_ticker,
    _f_lower_third,
    _f_typewriter_text,
    _f_bounce_text,
    _f_fade_text,
    _f_karaoke_text,
)

from .encoding import (  # noqa: F401
    _f_compress,
    _f_convert,
    _f_bitrate,
    _f_quality,
    _f_gif,
    _f_container,
    _f_two_pass,
    _f_audio_codec,
    _f_hwaccel,
    _f_thumbnail,
    _f_extract_frames,
)

from .presets import (  # noqa: F401
    _f_fade_to_black,
    _f_fade_to_white,
    _f_flash,
    _f_spin,
    _f_shake,
    _f_pulse,
    _f_bounce,
    _f_drift,
    _f_iris_reveal,
    _f_wipe,
    _f_slide_in,
)

from .spatial import (  # noqa: F401
    _f_resize,
    _f_crop,
    _f_pad,
    _f_rotate,
    _f_flip,
    _f_zoom,
    _f_ken_burns,
    _f_mirror,
    _f_caption_space,
    _f_lens_correction,
    _f_deinterlace,
    _f_frame_interpolation,
    _f_scroll,
    _f_aspect,
    _f_perspective,
    _f_fill_borders,
    _f_deshake,
    _f_frame_blend,
)

from .temporal import (  # noqa: F401
    _f_trim,
    _f_speed,
    _f_reverse,
    _f_loop,
    _f_boomerang,
    _f_jump_cut,
    _f_beat_sync,
)

from .visual import (  # noqa: F401
    _f_brightness,
    _f_contrast,
    _f_saturation,
    _f_hue,
    _f_sharpen,
    _f_blur,
    _f_denoise,
    _f_vignette,
    _f_fade,
    _f_pixelate,
    _f_posterize,
    _f_color_grade,
    _f_chromakey_simple,
    _f_deband,
    _f_color_temperature,
    _f_selective_color,
    _f_monochrome,
    _f_chromatic_aberration,
    _f_sketch,
    _f_glow,
    _f_ghost_trail,
    _f_color_channel_swap,
    _f_tilt_shift,
    _f_false_color,
    _f_halftone,
    _f_neon_enhanced,
    _f_thermal_enhanced,
    _f_comic_book_enhanced,
    _f_waveform,
    _f_chromakey,
    _f_blend,
    _f_color_match,
    _f_datamosh,
    _f_mask_blur,
    _f_lut_apply,
    _f_colorkey,
    _f_lumakey,
    _f_colorhold,
    _f_despill,
    _f_remove_background,
)

