name: film_burn
description: "Simulate a film burn / light leak by boosting exposure and adding warm color shift"
category: creative
aliases: [light_leak, burn_effect]
tags: [film, burn, leak, light, analog, retro]
examples:
  - "film_burn - Default film burn effect"
  - "film_burn:intensity=0.8,color=warm - Strong warm burn"
  - "film_burn:color=cool - Cool light leak"

parameters:
  intensity:
    type: float
    description: "Burn intensity"
    default: 0.5
    min: 0.1
    max: 1.0
  color:
    type: choice
    description: "Burn color temperature"
    default: warm
    choices: [warm, cool, neutral]

# Composite pipeline: chain multiple built-in skills
pipeline:
  - "brightness:value={intensity}"
  - "colorbalance:rs={intensity},gs=0.05,bs=-0.1"
  - "saturation:value=1.2"
