"""Type stub for ComfyUI's folder_paths module."""

from typing import Any

def get_output_directory() -> str: ...
def get_input_directory() -> str: ...
def get_temp_directory() -> str: ...
def get_folder_paths(folder_name: str) -> list[str]: ...
def get_filename_list(folder_name: str) -> list[str]: ...
def get_full_path(folder_name: str, filename: str) -> str | None: ...
def add_model_folder_path(folder_name: str, full_folder_path: str) -> None: ...
def get_save_image_path(
    filename_prefix: str,
    output_dir: str,
    image_width: int = ...,
    image_height: int = ...,
) -> tuple[str, str, int, str, str]: ...
def get_annotated_filepath(name: str) -> str: ...
def exists_annotated_filepath(name: str) -> bool: ...
def filter_files_content_types(
    files: list[str], content_types: list[str]
) -> list[str]: ...

models_dir: str
