"""Type stub for comfy.model_management."""

import torch

def get_torch_device() -> torch.device: ...
def unet_offload_device() -> torch.device: ...
def soft_empty_cache(force: bool = False) -> None: ...
def load_models_gpu(models: list, memory_required: int = ...) -> None: ...
def should_use_fp16(device: torch.device | None = None) -> bool: ...
def vae_dtype(device: torch.device | None = None) -> torch.dtype: ...
def text_encoder_dtype(device: torch.device | None = None) -> torch.dtype: ...
def intermediate_device() -> torch.device: ...
def get_free_memory(dev: torch.device | None = None) -> int: ...
def unload_all_models() -> None: ...
