"""Type stub for comfy.utils."""

from typing import Any

class ProgressBar:
    def __init__(self, total: int) -> None: ...
    def update(self, value: int = 1) -> None: ...
    def update_absolute(self, value: int, total: int | None = None) -> None: ...

def load_torch_file(path: str, safe_load: bool = True) -> dict[str, Any]: ...
